//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL= 'REGISTRATION_SUCCESS';

//dashboard
export const USER_PROFILE_START = 'USER_PROFILE_START';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//builder
export const SELECT_GRID_TYPE = 'SELECT_GRID_TYPE';
export const DROP_ITEM = 'DROP_ITEM'
export const CHANGE_STYLE_ITEM = 'CHANGE_STYLE_ITEM'
export const SELECT_ITEM = 'SELECT_ITEM'
export const CHANGE_CONTENT_ITEM = 'CHANGE_CONTENT_ITEM';
export const TEMPLATE_IN_JSON = 'TEMPLATE_IN_JSON';
export const JSON_IN_TEMPLATE = 'JSON_IN_TEMPLATE';
export const SAVE_HTML = 'SAVE_HTML';
export const REORDER_COLUMN_ITEMS = 'REORDER_COLUMN_ITEMS'

//templates
export const FETCH_TEMPLATES_START = 'FETCH_TEMPLATES_START'
export const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS'
export const FETCH_TEMPLATES_FAIL = 'FETCH_TEMPLATES_FAIL'
export const SELECT_TEMPLATE = 'SELECT_TEMPLATE'

//sagas
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const REGISTRATION_USER = 'REGISTRATION_USER'
export const AUTH_USER  = 'AUTH_USER'
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const USER_PROFILE = 'USER_PROFILE';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES'